name: native_http
description: A new flutter plugin project.
version: 0.0.3
author: Aawaz Gyawali <awazgyawali@gmail.com>
homepage: https://github.com/awazgyawali/native_http

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.brainants.nativehttp.native_http
    pluginClass: NativeHttpPlugin
